# Generated by Django 4.0.4 on 2022-04-12 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numberHouse', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('biography', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('publicationDate', models.DateField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('numberOfPage', models.IntegerField()),
                ('author', models.ManyToManyField(to='shop.author')),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='BookItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('description', models.CharField(max_length=255)),
                ('numberSold', models.IntegerField()),
                ('numAvailidInStock', models.IntegerField()),
                ('images', models.ImageField(upload_to='backend/shop/uploads')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.book')),
            ],
            options={
                'db_table': 'bookitem',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('totalPrice', models.FloatField()),
                ('books', models.ManyToManyField(to='shop.bookitem')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='CategoryBook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'categorybook',
            },
        ),
        migrations.CreateModel(
            name='CategoryClothes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'categoryclothes',
            },
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=255)),
                ('marterial', models.CharField(max_length=255)),
                ('countryOfOrigin', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('importPrice', models.FloatField()),
                ('color', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'clothes',
            },
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('techType', models.CharField(max_length=255)),
                ('typeCpu', models.CharField(max_length=255)),
                ('speed', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cpu',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=255)),
                ('mail', models.CharField(max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.account')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.address')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='FullName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fisrtName', models.CharField(max_length=255)),
                ('midName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'fullname',
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('screen', models.CharField(max_length=255)),
                ('battery', models.CharField(max_length=255)),
                ('weight', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('warranty', models.CharField(max_length=255)),
                ('ops', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('ram', models.CharField(max_length=255)),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cpu')),
            ],
            options={
                'db_table': 'laptop',
            },
        ),
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('ram', models.CharField(max_length=255)),
                ('cpu', models.CharField(max_length=255)),
                ('screen', models.CharField(max_length=255)),
                ('rearCamera', models.CharField(max_length=255)),
                ('frontCamera', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('ops', models.CharField(max_length=255)),
                ('battery', models.CharField(max_length=255)),
                ('warranty', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('displayType', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'mobilephone',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'publisher',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cost', models.FloatField()),
                ('type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'shipment',
            },
        ),
        migrations.CreateModel(
            name='VGA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('vram', models.CharField(max_length=255)),
                ('tech', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'vga',
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('discountPercent', models.FloatField()),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'voucher',
            },
        ),
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('clothes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='shop.clothes')),
                ('dressId', models.AutoField(primary_key=True, serialize=False)),
                ('typeSleeves', models.CharField(max_length=255)),
                ('chestMeasurements', models.FloatField()),
                ('waistMeasurements', models.FloatField()),
                ('buttMeasurements', models.FloatField()),
                ('length', models.FloatField()),
                ('shape', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dress',
            },
            bases=('shop.clothes',),
        ),
        migrations.CreateModel(
            name='Pant',
            fields=[
                ('clothes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='shop.clothes')),
                ('paintId', models.AutoField(primary_key=True, serialize=False)),
                ('thighMeasurements', models.FloatField()),
                ('waistMeasurements', models.FloatField()),
                ('buttMeasurements', models.FloatField()),
                ('length', models.FloatField()),
            ],
            options={
                'db_table': 'pant',
            },
            bases=('shop.clothes',),
        ),
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('clothes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='shop.clothes')),
                ('shirtId', models.AutoField(primary_key=True, serialize=False)),
                ('sleevesLength', models.FloatField()),
                ('chestMeasurements', models.FloatField()),
                ('length', models.FloatField()),
                ('collarType', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'shirt',
            },
            bases=('shop.clothes',),
        ),
        migrations.CreateModel(
            name='Skirt',
            fields=[
                ('clothes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='shop.clothes')),
                ('skirtId', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('waistMeasurements', models.FloatField()),
                ('buttMeasurements', models.FloatField()),
                ('length', models.FloatField()),
            ],
            options={
                'db_table': 'skirt',
            },
            bases=('shop.clothes',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('totalAmount', models.FloatField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.address')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cart')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.payment')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shipment')),
                ('voucher', models.ManyToManyField(to='shop.voucher')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='MobilePhoneItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('description', models.CharField(max_length=255)),
                ('numberSold', models.IntegerField()),
                ('numAvailidInStock', models.IntegerField()),
                ('images', models.ImageField(upload_to='backend/shop/uploads')),
                ('mobilePhone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.mobilephone')),
            ],
            options={
                'db_table': 'mobilephoneitem',
            },
        ),
        migrations.CreateModel(
            name='LaptopItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('description', models.CharField(max_length=255)),
                ('numberSold', models.IntegerField()),
                ('numAvailidInStock', models.IntegerField()),
                ('images', models.ImageField(upload_to='backend/shop/uploads')),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.laptop')),
            ],
            options={
                'db_table': 'laptopitem',
            },
        ),
        migrations.AddField(
            model_name='laptop',
            name='vga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.vga'),
        ),
        migrations.AddField(
            model_name='customer',
            name='fullName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.fullname'),
        ),
        migrations.CreateModel(
            name='ClothesItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('description', models.CharField(max_length=255)),
                ('numberSold', models.IntegerField()),
                ('numAvailidInStock', models.IntegerField()),
                ('images', models.ImageField(upload_to='backend/shop/uploads')),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.clothes')),
            ],
            options={
                'db_table': 'clothesitem',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='clothes',
            field=models.ManyToManyField(to='shop.clothesitem'),
        ),
        migrations.AddField(
            model_name='cart',
            name='laptops',
            field=models.ManyToManyField(to='shop.laptopitem'),
        ),
        migrations.AddField(
            model_name='cart',
            name='mobliePhones',
            field=models.ManyToManyField(to='shop.mobilephoneitem'),
        ),
        migrations.AddField(
            model_name='book',
            name='categoryBookId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.categorybook'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisherId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.publisher'),
        ),
    ]
